export default {
  isdev: ["development"].includes(process.env.NODE_ENV),
  // isdev: true,
  icons: [
    "iconfont iconfont-tuandui",
    "iconfont iconfont-dizhi",
    "iconfont iconfont-hezi",
    "iconfont iconfont-shengchanjiaojie",
    "iconfont iconfont-biaoqian",
    "iconfont iconfont-huoweiyingshe",
    "iconfont iconfont-U9renwuhexin",
    "iconfont iconfont-tuopanguanli",
    "iconfont iconfont-zhidingjihua",
    "iconfont iconfont-quanxianfenpei",
    "iconfont iconfont-tubiaoguanli",
    "iconfont iconfont-zhijianzhibiao",
    "iconfont iconfont-shouhuoguanli",
    "iconfont iconfont-cailiaogaofenzichengfen",
    "iconfont iconfont-cailiaoyuansuchengfendangan",
    "iconfont iconfont-wuliaobiaoqian",
    "iconfont iconfont-ditu",
    "iconfont iconfont-zhuzhuangtu",
    "iconfont iconfont-zuzhi",
    "iconfont iconfont-gongxuliucheng",
    "iconfont iconfont-gongchangjianmo",
    "iconfont iconfont-xitongguanli",
  ],
  theme: {
    light: {
      primary: "#fff",
      assist: "#e0e0e0",
      color: "#222",
    },
    blue: {
      assist: "#c7e0f4",
      primary: "#0078d4",
      color: "#fff",
    },
    lightblue: {
      assist: "#C6E4FF",
      primary: "#5DB2FF",
      color: "#fff",
    },
    pink: {
      assist: "#F2C3E2",
      primary: "#DC4FAD",
      color: "#fff",
    },
    green: {
      assist: "#BEE3D8",
      primary: "#5FBCA2",
      color: "#fff",
    },
  },
};
