export default {
  isdev: ["development"].includes(process.env.NODE_ENV),
  tp: {
    role: {
      path: "/role",
      tp: "角色模板",
      en: "role",
    },
    faction: {
      path: "/faction",
      tp: "势力模板",
      en: "faction",
    },
    realm: {
      path: "/realm",
      tp: "境界模板",
      en: "realm",
    },
    year: {
      path: "/year",
      tp: "时间线模板",
      en: "year",
    },
    page: {
      path: "/page",
      tp: "单页模板",
      en: "page",
    },
  },
  icons: [
    "iconfont iconfont-tuandui",
    "iconfont iconfont-dizhi",
    "iconfont iconfont-hezi",
    "iconfont iconfont-shengchanjiaojie",
    "iconfont iconfont-biaoqian",
    "iconfont iconfont-huoweiyingshe",
    "iconfont iconfont-U9renwuhexin",
    "iconfont iconfont-tuopanguanli",
    "iconfont iconfont-zhidingjihua",
    "iconfont iconfont-quanxianfenpei",
    "iconfont iconfont-tubiaoguanli",
    "iconfont iconfont-zhijianzhibiao",
    "iconfont iconfont-shouhuoguanli",
    "iconfont iconfont-cailiaogaofenzichengfen",
    "iconfont iconfont-cailiaoyuansuchengfendangan",
    "iconfont iconfont-wuliaobiaoqian",
    "iconfont iconfont-ditu",
    "iconfont iconfont-zhuzhuangtu",
    "iconfont iconfont-zuzhi",
    "iconfont iconfont-gongxuliucheng",
    "iconfont iconfont-gongchangjianmo",
    "iconfont iconfont-xitongguanli",
  ],
};
